spring:
  datasource:
    url: ${DATABASE_URL}/${DATABASE_NAME}
    username: ${DATABASE_NAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  kafka:
    producer:
      bootstrap-servers: microservices-crm-message-broker:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: contactFromLead:org.example.accountservice.event.ContactFromLead

    consumer:
      bootstrap-servers: microservices-crm-message-broker:9092
      group-id: lead-qualified-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: qualifiedLead:org.example.accountservice.event.QualifiedLead

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL}

server:
  port: 8083
  servlet:
    context-path: /api/accounts

springdoc:
  api-docs:
    enabled: true
    path: /api/accounts/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/accounts/swagger-ui.html