spring:
  datasource:
    url: ${DATABASE_URL}/${DATABASE_NAME}
    username: ${DATABASE_NAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL}

server:
  port: 8083
  servlet:
    context-path: /api/accounts

springdoc:
  api-docs:
    enabled: true
    path: /api/accounts/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/accounts/swagger-ui.html