spring:
  datasource:
    url: ${DATABASE_URL}/${DATABASE_NAME}
    username: ${DATABASE_NAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  kafka:
    producer:
      bootstrap-servers: microservices-crm-message-broker:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: qualifiedLead:org.example.leadservice.event.QualifiedLead

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL}

server:
  port: 8084
  servlet:
    context-path: /api/leads

springdoc:
  api-docs:
    enabled: true
    path: /api/leads/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/leads/swagger-ui.html