spring:

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL}

server:
  port: 8081
  servlet:
    context-path: /api/users

springdoc:
  api-docs:
    enabled: true
    path: /api/users/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/users/swagger-ui.html

app:
  auth-server:
    url: ${AUTH_SERVER_URL}
    realm: ${AUTH_SERVER_REALM}
    client-id: ${AUTH_SERVER_API_CLIENT_ID}
    client-secret: ${AUTH_SERVER_API_CLIENT_SECRET}